config/routes.rb
Rails.application.routes.draw do
  root 'pages#top'

  devise_scope :user do
    get '/sign_in', :to => 'users/sessions#new'
    post '/sign_in', :to => 'users/sessions#create'
    get '/sign_out', :to => 'users/sessions#destroy'

    get '/passwords/edit', :to => 'users/registrations#edit'
    patch '/passwords/update', :to => 'users/registrations#update'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/mypage', to: 'pages#mypage'

  namespace :admin do
    root 'pages#top'
    resources :books
    resources :users
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :books, constraints: {id: /\d*/}, only: [:show]
      get '/books/index_or_search', to: 'books#index_or_search'
      post '/books/:id/borrow', to: 'books#borrow'
      post '/books/:id/return', to: 'books#return'
      post '/request', to: 'requests#create'
      post '/comments', to:'comments#create'
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :rents, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum status: {
    broken: -2,
    before_shelf: -1,
    in_shelf: 0,
    in_use:1
  }
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController

  def index
    @books = Book.all.order(created_at: :desc).paginate(page: params[:page])
  end

  def new
    @book = Book.new
  end

  def create
    # isbnを一括で取得
    isbn_code_set = params[:isbn]

    # isbnを元にamazon apiから書籍情報を一括取得
    # Bookインスタンスのarrayとして取得
    books = AmazonApi.getBooks(isbn_code_set)

    # それぞれurlからスクレイプしたカテゴリを取得
    books.each do |b|
      url = b.url
      b.categories << AmazonApi.getCategoryFromAmazon(b.url)
    end

    if books.save
      redirect_to admin_root_path, notice:'保存できました'
    else
      render 'new', alert: '保存できませんでした'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to admin_root_path, notice:'保存できました'
    else
      render 'edit', alert: '保存できませんでした'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_path, notice: "#{@book.title}を削除しました"
  end

  private

  def book_params
    params.require(:book).permit(:isbn10,:isbn13,:title,:author,:published_at,:publisher,:status,:hires_image,:large_image,:description,:url,:category)
  end

  def authenticate_admin!
    if !user_signed_in? || !current_user.admin?
      redirect_to root_path, notice: 'このページにはアクセスできません'
    end
  end
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
  before_filter :authenticate_user!
  protect_from_forgery except: [:borrow, :return]
  include NoticeToSlack

  def index_or_search
    if params[:query][:search_key].blank?
      @books = Book.eager_load(:rents, :comments).all.order(created_at: :desc).paginate(page: params[:page])
    elsif
      @books = Book.eager_load(:rents, :comments).search({
                      title_or_author_or_publisher_cont: params[:query][:search_key]
                   }).result.order(created_at: :desc).paginate(page: params[:page])
    end
    set_count @books
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments
  end

  def borrow
    book_id = params[:id]
    user_id = current_user.id

    # 既にレンタルしていないかチェック
    rent = Rent.search({
      book_id_eq: book_id,
      user_id_eq: user_id,
      ended_at_not_null: true
    }).result
    if !rent.blank?
      @message = '既に借りています'
      return
    end

    rent = Rent.new(
      book_id: book_id,
      user_id: user_id,
      start_at: Date.today,
      end_at: Date.today + 7
    )
    if rent.save
      Book.find(book_id).in_use!
      @message = '貸し出ししました。'
      NoticeToSlack.on_book_borrow rent
    else
      @message = '貸出に失敗しました。'
    end
  end

  def return
    book = Book.find(params[:id])
    book.in_shelf!
    rent = Rent.where(user_id: current_user.id, book_id: book.id, ended_at: nil).last
    rent.returned!
    @message = '返却しました。'
    NoticeToSlack.on_book_return rent
  end

  private
  def set_count books
    @total =  books.count
    @left_count = @total - (params[:page].to_i) * 30 # 1ページにつき30件返す
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/api/v1/books_helper.rb
module Api::V1::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def book_image book
    if book.hires_image
      book.hires_image
    elsif book.large_image
      book.large_image
    else
      nil
    end
  end

  def book_author book
    if book.author.nil?
      if book.publisher.nil?
        '著者不明'
      else
        book.publisher
      end
    else
      book.author
    end
  end

  def book_category book
    book.category.nil? ? 'カテゴリ不明' : book.category
  end

  def book_comment_num book
    if book.comments.count == 0
      'コメント無し><'
    else
      book.comments.count.to_s + "件のコメント"
    end
  end
end

app/views/admin/books/_book_form.html.erb
<div class="form--table <%= (mini) ? 'mini': nil %>">
  <div class="form--body">
    <%= form_for [:admin, book] do |f| %>
      <div class="form--cell">
        <%= f.label :title, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :title, class: "mdl-textfield__input", id: 'title' %>
          <label class="mdl-textfield__label" for="title">title...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :isbn10, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :isbn10, class: "mdl-textfield__input", id: 'isbn10' %>
          <label class="mdl-textfield__label" for="isbn10">isbn10...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :isbn13, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :isbn13, class: "mdl-textfield__input", id: 'isbn13' %>
          <label class="mdl-textfield__label" for="isbn13">isbn13...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :author, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :author, class: "mdl-textfield__input", id: 'author' %>
          <label class="mdl-textfield__label" for="author">author...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :category, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :category, class: "mdl-textfield__input", id: 'category' %>
          <label class="mdl-textfield__label" for="category">category...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :hires_image, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :hires_image, class: "mdl-textfield__input", id: 'hires_image' %>
          <label class="mdl-textfield__label" for="hires_image">category...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :large_image, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :large_image, class: "mdl-textfield__input", id: 'large_image' %>
          <label class="mdl-textfield__label" for="large_image">large_image...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :description, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :description, class: "mdl-textfield__input", id: 'description' %>
          <label class="mdl-textfield__label" for="description">description...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :url, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :url, class: "mdl-textfield__input", id: 'url' %>
          <label class="mdl-textfield__label" for="url">url...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :publisher, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :publisher, class: "mdl-textfield__input", id: 'publisher' %>
          <label class="mdl-textfield__label" for="publisher">publisher...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :published_at, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :published_at, class: "mdl-textfield__input", id: 'published_at' %>
          <label class="mdl-textfield__label" for="published_at">published_at...</label>
        </div>
      </div>
      <div class="form--cell">
        <%= f.label :status, class:"form--label" %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.text_field :status, class: "mdl-textfield__input", id: 'status' %>
          <label class="mdl-textfield__label" for="status">status...</label>
        </div>
      </div>
      <%= f.submit class:"mdl-button form--submit mdl-button--colored" %>
    <% end %>
  </div>
</div>

app/views/admin/books/_book_list.html.erb
<div class="list">
  <div class="mdl-grid list-header mdl-cell--hide-tablet mdl-cell--hide-phone">
    <div class="mdl-cell mdl-cell--4-col">タイトル</div>
    <div class="mdl-cell mdl-cell--2-col">著者</div>
    <div class="mdl-cell mdl-cell--2-col">カテゴリ</div>
    <div class="mdl-cell mdl-cell--2-col">ステータス</div>
    <div class="mdl-cell mdl-cell--2-col"></div>
  </div>
  <div class="list-body">
    <% books.each do |b| %>
      <div class="list-item mdl-grid">
        <div class="mdl-cell mdl-cell--4-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <span class="list-item--label mdl-cell--hide-desktop">タイトル</span>
          <span class="list-item--text"><%= b.title %></span>
        </div>
        <div class="mdl-cell mdl-cell--2-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <span class="list-item--label mdl-cell--hide-desktop">著者</span>
          <span class="list-item--text"><%= b.author %></span>
        </div>
        <div class="mdl-cell mdl-cell--2-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <span class="list-item--label mdl-cell--hide-desktop">カテゴリ</span>
          <span class="list-item--text">未取得</span>
        </div>
        <div class="mdl-cell mdl-cell--2-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <span class="list-item--label mdl-cell--hide-desktop">ステータス</span>
          <span class="list-item--text"><%= b.status_i18n %></span>
          <% if (b.in_use?) %>
          <%= content_tag(
                :span,
                "(" + Rent.search(book_id_eq:b.id, ended_at_null:true).result.last.user.family_name + ")",
                class:"list-itme--text"
              )%>
          <% end %>
        </div>
        <div class="mdl-cell mdl-cell--2-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <%= link_to "編集する", edit_admin_book_path(b)%>
          <%= link_to "削除する", admin_book_path(b), method: :delete, data:{confirm:'本当に削除しますか？'}%>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= will_paginate @books,
                  previous_label: content_tag(:i, 'keyboard_arrow_left', class:"material-icons"),
                  next_label: content_tag(:i, 'keyboard_arrow_right', class:"material-icons") %>

app/views/admin/books/edit.html.erb
<div class="container narrow">
  <div class="title-section">
    <h1 class="title-section--title">本を編集する</h1>
    <%= link_to admin_books_path, class: "title-section--link" do %>
         書籍一覧に戻る
    <% end %>
  </div>
  <%= render partial:'book_form', locals:{book: @book, mini:false} %>
</div>

app/views/admin/books/index.html.erb
<div class="container">
  <div class="title-section">
    <h1 class="title-section--title">ユーザー一覧</h1>
    <%= link_to new_admin_book_path, class: "title-section--link" do %>
         <i class="material-icons">add_circle_outline</i>書籍を追加する
    <% end %>
  </div>
  <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
    <%= render partial:'book_list', locals:{books: @books} %>
  </div>
</div>

app/views/admin/books/new.html.erb
<div class="container narrow">
  <div class="title-section">
    <h1 class="title-section--title">本を追加する</h1>
    <%= link_to admin_books_path, class: "title-section--link" do %>
         書籍一覧に戻る
    <% end %>
  </div>
  <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
  <div class="mdl-tabs__tab-bar">
      <a href="#isbn" class="mdl-tabs__tab is-active">isbn</a>
      <a href="#manual" class="mdl-tabs__tab">マニュアル</a>
  </div>

  <div class="mdl-tabs__panel is-active" id="isbn">
    <div class="mdl-textfield mdl-js-textfield">
      <textarea class="mdl-textfield__input" type="text" rows= "3" id="isbn-list" ></textarea>
      <label class="mdl-textfield__label" for="isbn-list">ISBN10を改行で貼付け</label>
    </div>
    <div class="results">
      <%= render partial:'book_form', locals:{book: @book, mini: true} %>
    </div>
  </div>
  <div class="mdl-tabs__panel" id="manual">
    <%= render partial:'book_form', locals:{book: @book, mini:false} %>
  </div>
</div>
</div>