config/routes.rb
Rails.application.routes.draw do
  root 'pages#top'

  devise_scope :user do
    get '/sign_in', :to => 'users/sessions#new'
    post '/sign_in', :to => 'users/sessions#create'
    get '/sign_out', :to => 'users/sessions#destroy'

    get '/passwords/edit', :to => 'users/registrations#edit'
    patch '/passwords/update', :to => 'users/registrations#update'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/mypage', to: 'pages#mypage'

  namespace :admin do
    root 'pages#top'
    resources :books
    resources :users
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :books, constraints: {id: /\d*/}, only: [:show]
      get '/books/index_or_search', to: 'books#index_or_search'
      post '/books/:id/borrow', to: 'books#borrow'
      post '/books/:id/return', to: 'books#return'
      post '/request', to: 'requests#create'
      post '/comments', to:'comments#create'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowtvLibrary</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- google material design lite -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <!-- /google material design lite -->
</head>
<body class="<%= params[:controller].split('/').first %> <%= params[:controller].split('/').last %> <%= params[:action] %>">
<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <% if !hide_header %>
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">
        <%= link_to "Howtv Library", root_path %>
      </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation"> <!--mdl-layout--large-screen-only-->
        <% if user_signed_in? %>
          <%= link_to content_tag(:i, 'settings', class:"material-icons"), passwords_edit_path, class:'mdl-navigation__link', id:"account" %>
          <div class="mdl-tooltip" for="account">change password and email</div>
          <%= link_to content_tag(:i, 'notifications', class:"material-icons"), "#", class:'mdl-navigation__link', id:"notification" %>
          <div class="mdl-tooltip" for="notification">通知欲しいですか？</div>
          <%= link_to content_tag(:i, 'exit_to_app', class:"material-icons"), sign_out_path, method: :delete, class:'mdl-navigation__link', id:"signout"%>
          <div class="mdl-tooltip" for="signout">sign out</div>
        <% else %>
          <%= link_to "ログイン", sign_in_path, class:'mdl-navigation__link', id:"signin" %>
          <div class="mdl-tooltip" for="signin">sign in</div>
        <% end %>
      </nav>
    </div>
  </header>
  <% end %>
  <% if user_signed_in? %>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">
      <%= link_to "Howtv Library", root_path %>
    </span>
    <nav class="mdl-navigation">
      <%= link_to 'マイページ', mypage_path, class:'mdl-navigation__link' %>
      <%= link_to '本を探す', root_path, class:'mdl-navigation__link' %>
      <%= link_to 'アカウント設定', passwords_edit_path, class:'mdl-navigation__link' %>
      <%= link_to "ログアウト", sign_out_path, method: :delete, class:'mdl-navigation__link' %>
      <% if current_user.admin? %>
        <%= link_to "管理画面", admin_root_path, class:'mdl-navigation__link' %>
      <% end %>
    </nav>
  </div>
  <% end %>

  <main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
      <% if !notice.nil? %>
        <div class="notice notice-box">
          <div class="container"><%= notice %></div>
        </div>
      <% end %>
      <% if !alert.nil? %>
        <div class="alert notice-box">
          <div class="container"><%= alert %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <% if !hide_header %>
      <div id="request" v-bind:class="{'close': !showRequest}">
        <div class="panel">
          <h2 class="panel--title">
            リクエスト
            <span class="close-request">
              <button class="mdl-button mdl-js-button mdl-button--icon" v-on:click="toggleRequest()">
                <i class="material-icons">close</i>
              </button>
            </span>
          </h2>
          <div class="panel--form">
            <div class="mdl-textfield mdl-js-textfield">
              <select class="mdl-textfield__input" v-model="query.type">
                <option value="0">書籍のリクエスト</option>
                <option value="1">バグ報告</option>
                <option value="2">機能アイデア</option>
                <option value="3">ねぎらい</option>
              </select>
            </div>
            <div class="mdl-textfield mdl-js-textfield">
              <textarea class="mdl-textfield__input" type="text" rows= "3" id="request-text" v-model="query.body"></textarea>
              <label class="mdl-textfield__label" for="request-text">Text lines...</label>
            </div>
            <button class="mdl-button submit" v-bind:disabled="!query.body" v-on:click="sendRequest">{{(!query.body) ? 'コメントを入力' : '送信'}}</button>
          </div>
        </div>
      </div>
    <% end %>
  </main>
</div>

</body>
</html>